### ISSUE TITLE
[BUG] Open device/file nodes leaks 32 bytes of memory

### ISSUE THREAD

**Issue by sebastianene07** [SebiEne/cat_os#20]
**Describe the bug**
Heap memory leaks when we open/close files.

**Screenshots**
root:#/>sensor_measure
Received 0 bytes from sensor
root:#/>free
Free size | Used size | Largest Free Chunk | Total
223536 bytes | 3840 bytes | 223456 bytes | 227600 bytes

root:#/>sensor_measure
Received 0 bytes from sensor
root:#/>free
Free size | Used size | Largest Free Chunk | Total
223472 bytes | 3872 bytes | 223376 bytes | 227600 bytes

**Comment by sebastianene07** [comment]
`
Breakpoint 1, malloc (size=size@entry=12) at stdlib.c:18
18	{
(gdb) bt
#0  malloc (size=size@entry=12) at stdlib.c:18
#1  0x000050f0 in calloc (nmemb=nmemb@entry=1, size=<optimized out>) at stdlib.c:35
#2  0x0000574a in vfs_get_matching_node (name=name@entry=0x258 "/dev/bme680", name_len=11) at vfs.c:106
#3  0x0000500e in open (pathname=pathname@entry=0x258 "/dev/bme680", flags=0) at stat.c:22
#4  0x00001eb4 in console_sensor_measure (argc=<optimized out>, argv=<optimized out>) at console_sensor_measure.c:19
#5  0x00001b70 in execute_command (argv=<optimized out>, argc=<optimized out>) at console_main.c:129
#6  parse_arguments (newline=<optimized out>, buffer=0x200011f0 "sensor_measure") at console_main.c:181
#7  console_main () at console_main.c:231
#8  0x0000453c in sched_idle_task () at scheduler.c:61
#9  0x00000000 in ?? ()
(gdb) c
Continuing.

Breakpoint 1, malloc (size=size@entry=20) at stdlib.c:18
18	{
(gdb) bt
#0  malloc (size=size@entry=20) at stdlib.c:18
#1  0x000050f0 in calloc (nmemb=nmemb@entry=1, size=size@entry=20) at stdlib.c:35
#2  0x00004674 in sched_allocate_resource (vfs_node=vfs_node@entry=0x20000a30, open_mode=open_mode@entry=0) at scheduler.c:382
#3  0x00005018 in open (pathname=pathname@entry=0x258 "/dev/bme680", flags=0) at stat.c:30
#4  0x00001eb4 in console_sensor_measure (argc=<optimized out>, argv=<optimized out>) at console_sensor_measure.c:19
#5  0x00001b70 in execute_command (argv=<optimized out>, argc=<optimized out>) at console_main.c:129
#6  parse_arguments (newline=<optimized out>, buffer=0x200011f0 "sensor_measure") at console_main.c:181
#7  console_main () at console_main.c:231
#8  0x0000453c in sched_idle_task () at scheduler.c:61
#9  0x00000000 in ?? ()
`
